### ISSUE TITLE
Add km2 to variable list in Naturtype - detaljert

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/naturtypedata#1]
Add "km2" to varList2 and add an ifelse in ntyp_utvalg to switch to geom_histogram if variable1 == km2.

**Comment by anders-kolstad** [comment]
@DrMattG can you help me with this? I thought i had done it before I left but apparently I forgot.

**Comment by DrMattG** [comment]
Added changes and after a struggle to get permission I have now uploaded these to the internal server. Closing this now.
